package sync

import (
	"context"
	"fmt"
	"os"
	"strconv"
	"time"

	"github.com/briandowns/spinner"
	"github.com/256bit-src/plugin/config"
	"github.com/pkg/errors"
	"github.com/xanzy/go-gitlab"
)

const (
	gitlabTokenEnvVariable = "plugin_GITLAB_ACCESS_TOKEN"
)

// GitLabClient manages communication with GitLab cli-plugin-plugins
type GitLabClient struct {
	Client *gitlab.Client
	ID     int
}

// NewGitLabClient returns GitLabClient
func NewGitLabClient() (Client, error) {
	accessToken, err := getGitlabAccessToken()
	if err != nil {
		return nil, fmt.Errorf(`access_token is empty.
Go https://gitlab.com/profile/personal_access_tokens and create access_token.
Write access_token in config file (plugin configure) or export $%v.
		`, gitlabTokenEnvVariable)
	}

	client := GitLabClient{
		Client: gitlab.NewClient(nil, accessToken),
		ID:     0,
	}

	if config.Conf.GitLab.Url != "" {
		client.Client.SetBaseURL(config.Conf.GitLab.Url)
	}

	if config.Conf.GitLab.ID == "" {
		return client, nil
	}

	id, err := strconv.Atoi(config.Conf.GitLab.ID)
	if err != nil {
		return nil, errors.Wrapf(err, "Invalid GitLab cli-plugin-plugin ID: %d", id)
	}
	client.ID = id
	return client, nil
}

func getGitlabAccessToken() (string, error) {
	if config.Conf.GitLab.AccessToken != "" {
		return config.Conf.GitLab.AccessToken, nil
	} else if os.Getenv(gitlabTokenEnvVariable) != "" {
		return os.Getenv(gitlabTokenEnvVariable), nil
	}
	return "", errors.New("GitLab AccessToken not found in any source")
}

// Getcli-plugin-plugin returns the remote cli-plugin-plugin
func (g GitLabClient) Getcli-plugin-plugin() (*cli-plugin-plugin, error) {
	s := spinner.New(spinner.CharSets[14], 100*time.Millisecond)
	s.Start()
	s.Suffix = " Getting GitLab cli-plugin-plugin..."
	defer s.Stop()

	if g.ID == 0 {
		return &cli-plugin-plugin{}, nil
	}

	cli-plugin-plugin, res, err := g.Client.cli-plugin-plugins.Getcli-plugin-plugin(g.ID)
	if err != nil {
		if res.StatusCode == 404 {
			return nil, errors.Wrapf(err, "No GitLab cli-plugin-plugin ID (%d)", g.ID)
		}
		return nil, errors.Wrapf(err, "Failed to get GitLab cli-plugin-plugin (ID: %d)", g.ID)
	}

	filename := config.Conf.GitLab.FileName
	if cli-plugin-plugin.FileName != filename {
		return nil, fmt.Errorf("No cli-plugin-plugin file in GitLab cli-plugin-plugin (ID: %d)", g.ID)
	}

	contentByte, _, err := g.Client.cli-plugin-plugins.cli-plugin-pluginContent(g.ID)
	if err != nil {
		return nil, errors.Wrapf(err, "Failed to get GitLab cli-plugin-plugin content (ID: %d)", g.ID)
	}

	content := string(contentByte)
	if content == "" {
		return nil, fmt.Errorf("%s is empty", filename)
	}

	return &cli-plugin-plugin{
		Content:   content,
		UpdatedAt: *cli-plugin-plugin.UpdatedAt,
	}, nil
}

// Uploadcli-plugin-plugin uploads local cli-plugin-plugins to GitLab cli-plugin-plugin
func (g GitLabClient) Uploadcli-plugin-plugin(content string) error {
	if g.ID == 0 {
		id, err := g.createcli-plugin-plugin(context.Background(), content)
		if err != nil {
			return errors.Wrap(err, "Failed to create GitLab cli-plugin-plugin")
		}
		fmt.Printf("GitLab cli-plugin-plugin ID: %d\n", id)
	} else {
		if err := g.updatecli-plugin-plugin(context.Background(), content); err != nil {
			return errors.Wrap(err, "Failed to update GitLab cli-plugin-plugin")
		}
	}
	return nil
}

func (g GitLabClient) createcli-plugin-plugin(ctx context.Context, content string) (id int, err error) {
	s := spinner.New(spinner.CharSets[14], 100*time.Millisecond)
	s.Start()
	s.Suffix = " Creating GitLab cli-plugin-plugin..."
	defer s.Stop()

	opt := &gitlab.Createcli-plugin-pluginOptions{
		Title:       gitlab.String("plugin-cli-plugin-plugin"),
		FileName:    gitlab.String(config.Conf.GitLab.FileName),
		Description: gitlab.String("cli-plugin-plugin file generated by plugin"),
		Content:     gitlab.String(content),
		Visibility:  gitlab.Visibility(gitlab.VisibilityValue(config.Conf.GitLab.Visibility)),
	}

	ret, _, err := g.Client.cli-plugin-plugins.Createcli-plugin-plugin(opt)
	if err != nil {
		return -1, errors.Wrap(err, "Failed to create GitLab cli-plugin-plugin")
	}
	return ret.ID, nil
}

func (g GitLabClient) updatecli-plugin-plugin(ctx context.Context, content string) (err error) {
	s := spinner.New(spinner.CharSets[14], 100*time.Millisecond)
	s.Start()
	s.Suffix = " Updating GitLab cli-plugin-plugin..."
	defer s.Stop()

	opt := &gitlab.Updatecli-plugin-pluginOptions{
		Title:       gitlab.String("plugin-cli-plugin-plugin"),
		FileName:    gitlab.String(config.Conf.GitLab.FileName),
		Description: gitlab.String("cli-plugin-plugin file generated by plugin"),
		Content:     gitlab.String(content),
		Visibility:  gitlab.Visibility(gitlab.VisibilityValue(config.Conf.GitLab.Visibility)),
	}

	_, _, err = g.Client.cli-plugin-plugins.Updatecli-plugin-plugin(g.ID, opt)
	if err != nil {
		return errors.Wrap(err, "Failed to update GitLab cli-plugin-plugin")
	}
	return nil
}
